Lab.Demo.EF.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.Demo.EF.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab.Demo.EF.MVC/Controllers/RegionController.cs
using Lab.Demo.EF.Entities;
using Lab.Demo.EF.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Lab.Demo.EF.MVC.Controllers
{
    public class RegionController : Controller
    {
        private readonly RegionLogic context;


        public RegionController() => context = new RegionLogic();

        // GET: Region
        public ActionResult Index()
        {
            List<Region> regions = context.GetAll();

            return View(regions);
        }
        public ActionResult ModifyForm(Region region)
        {
            return View();
        }
        [HttpPost]
        public ActionResult Modify(Region region)
        {
            if(context.GetOne(region.RegionID) == null)
            {
                SetMessage("Modificar Región", "La región seleccionada no existe.", "alert alert-danger");
                return View("Notification");
            }
            context.update(region);
            SetMessage("Modificar Región", "La región ha sido actualizada.", "alert alert-success");
            return View("Notification");
        }
        public ActionResult CreateForm()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Region region)
        {
            if(context.GetOne(region.RegionID) != null)
            {
                SetMessage("Crear Región", "La región que se ingresó ya existe.", "alert alert-danger");
                return View("Notification");
            }
            context.Add(region);
            SetMessage("Crear Región", "La región ha sido creada con éxito.", "alert alert-success");
            return View("Notification");
        }
        [HttpPost]
        public JsonResult Delete(int RegionID, string RegionDescription)
        {
            Region region = context.GetOne(RegionID);
            string message; 
            if (region != null && region.RegionDescription.Trim() == RegionDescription)
            {
                context.delete(RegionID);
                message = "Region deleted successfully";
            }
            else
                message = "Region does not exist";
            return Json(message, JsonRequestBehavior.AllowGet);
        }
        private void SetMessage(string header, string message, string style)
        {
            ViewBag.Header = header;
            ViewBag.Message = message;
            ViewBag.MessageStyle = style;
        }
    }
}

Lab.Demo.EF.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab.Demo.EF.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab.Demo.EF.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Lab.Demo.EF.MVC/Views/Region/CreateForm.cshtml
@model Lab.Demo.EF.Entities.Region

@{
    ViewBag.Title = "CreateForm";
}

<h2>Crear Región</h2>

@using (Html.BeginForm("Create", "Region", FormMethod.Post, new { @class = "login-form" }))
{
    <div class="form-group">
        <label for="id">ID de la región:</label>
        @Html.TextBoxFor(m => m.RegionID, new { @id = "id", @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="description">Descripción de la región:</label>
        @Html.TextBoxFor(m => m.RegionDescription, new { @id = "id", @class = "form-control" })
    </div>
    <button type="submit" class=" btn btn-primary">Crear</button>
    @Html.ActionLink("Volver a Index", "Index", new { }, new { @class = "btn btn-primary" })
}

Lab.Demo.EF.MVC/Views/Region/Index.cshtml
@model IEnumerable<Lab.Demo.EF.Entities.Region>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Crear Región", "CreateForm", new { }, new { @class = "btn btn-success" })
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Descripción</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RegionID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegionDescription)
        </td>
        <td>
            @Html.ActionLink("Modificar", "ModifyForm", new Lab.Demo.EF.Entities.Region{ RegionID=item.RegionID, RegionDescription=item.RegionDescription.Trim() }, new { @class = "btn btn-warning" })
        </td>
        <td>
            <button class="btn btn-danger" onclick="DeleteRegion(@item.RegionID, '@item.RegionDescription.Trim()')">Eliminar</button>
        </td>
    </tr>
    }
</table>
<script>
    function DeleteRegion(id, description) {
         if (window.confirm("¿Realmente desea eliminar la región " + description + "?") == true) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Delete", "Region", null, Request.Url.Scheme)',
                data: {
                    RegionID: id,
                    RegionDescription: description
                },
                success: function (data) {
                    if (data == "Region deleted successfully") {
                        location.reload();
                    }
                    else if (data == "Region does not exist") {
                        //error
                    }
                    else {
                        //error
                    }
                },
                dataType: 'json'
            });
        }
    }
</script>

Lab.Demo.EF.MVC/Views/Region/ModifyForm.cshtml
@model Lab.Demo.EF.Entities.Region
@{
    ViewBag.Title = "ModifyForm";
}

<h2>Modificar Región</h2>

@using (Html.BeginForm("Modify", "Region", FormMethod.Post, new { @class = "login-form" }))
{
    <div class="form-group">
        <label for="id">ID de la región:</label>
        @Html.TextBoxFor(m => m.RegionID, new { @id = "id", @readonly = "readonly", @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="description">Descripción de la región:</label>
        @Html.TextBoxFor(m => m.RegionDescription, new { @id = "id", @class = "form-control" })
    </div>
    <button type="submit" class=" btn btn-primary">Modificar</button>
    @Html.ActionLink("Volver a Index", "Index", new { }, new { @class = "btn btn-primary" })
}

Lab.Demo.EF.MVC/Views/Region/Notification.cshtml
@{
    ViewBag.Title = "Notification";
}

<h2>@ViewBag.Header</h2>

<p class="@ViewBag.MessageStyle">
    @ViewBag.Message
</p>

@Html.ActionLink("Volver a Index", "Index", new { }, new { @class = "btn btn-primary" })

<script>
    $.(document).ready(function () {
        setTimeout(function(){
            window.location = @Url.Action("Delete", "Region", null, Request.Url.Scheme)
        }, 5000);
    })
</script>

Lab.Demo.EF.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Region", "Index", "Region")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
</body>
</html>